from django.db import models
from django.contrib.auth.models import User
class profile(models.Model):
    id_no = models.CharField(max_length=20)
    college_name = models.CharField(max_length=20)
    branch = models.CharField(max_length=20)
    year_of_study = models.CharField(max_length=20)
    gender = models.CharField(max_length=20)
    mobile = models.CharField(max_length=20)
    payment = models.CharField(max_length=10)
    pay_id = models.CharField(max_length=200)
    tt = models.CharField(max_length=10)
    sl = models.CharField(max_length=10)
    sb = models.CharField(max_length=10)
    tet = models.CharField(max_length=10)
    tc = models.CharField(max_length=10)
    deb = models.CharField(max_length=10)
    ipl = models.CharField(max_length=10)
    quiz = models.CharField(max_length=10)
    mp = models.CharField(max_length=10)
    ps = models.CharField(max_length=10)
    mmt = models.CharField(max_length=10)
    sg = models.CharField(max_length=10)
    rd = models.CharField(max_length=10)
    bgmi = models.CharField(max_length=10)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

class workshop(models.Model):
    name = models.CharField(max_length=80)
    payment = models.CharField(max_length=10)
    pay_id = models.CharField(max_length=200)
    tg=models.CharField(max_length=200)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
