# Generated by Django 3.2.8 on 2022-03-04 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='iplcount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('count', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tans_id', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('trans_time', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('payment', models.CharField(max_length=10)),
                ('pay_id', models.CharField(max_length=200)),
                ('tg', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='thrusangtank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.CharField(max_length=20)),
                ('college_name', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
                ('year_of_study', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('payment', models.CharField(max_length=10)),
                ('ttpay', models.CharField(max_length=10)),
                ('ttpay_id', models.CharField(max_length=100)),
                ('iplpay', models.CharField(max_length=10)),
                ('iplpay_id', models.CharField(max_length=100)),
                ('pay_id', models.CharField(max_length=200)),
                ('evpay', models.CharField(max_length=10)),
                ('evpay_id', models.CharField(max_length=200)),
                ('tt', models.CharField(max_length=10)),
                ('sl', models.CharField(max_length=10)),
                ('sb', models.CharField(max_length=10)),
                ('tet', models.CharField(max_length=10)),
                ('tc', models.CharField(max_length=10)),
                ('deb', models.CharField(max_length=10)),
                ('saw', models.CharField(max_length=10)),
                ('cg', models.CharField(max_length=10)),
                ('ipl', models.CharField(max_length=10)),
                ('quiz', models.CharField(max_length=10)),
                ('mp', models.CharField(max_length=10)),
                ('ld', models.CharField(max_length=10)),
                ('wb', models.CharField(max_length=10)),
                ('sg', models.CharField(max_length=10)),
                ('rd', models.CharField(max_length=10)),
                ('bgmi', models.CharField(max_length=10)),
                ('reg_time', models.CharField(max_length=100)),
                ('evcount', models.IntegerField()),
                ('ipcount', models.IntegerField()),
                ('th_id', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
