# Generated by Django 3.2.8 on 2023-02-20 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='thrusangtank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.CharField(max_length=20)),
                ('college_name', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
                ('year_of_study', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
                ('payment', models.CharField(max_length=10)),
                ('pay_id', models.CharField(max_length=200)),
                ('evpay', models.CharField(max_length=10)),
                ('reg_time', models.CharField(max_length=100)),
                ('evcount', models.IntegerField()),
                ('th_id', models.CharField(max_length=30)),
                ('ethical', models.CharField(max_length=10)),
                ('aurdino', models.CharField(max_length=10)),
                ('crtdrsk', models.CharField(max_length=10)),
                ('repair', models.CharField(max_length=10)),
                ('knowit', models.CharField(max_length=10)),
                ('cyber', models.CharField(max_length=10)),
                ('thrsngtnk', models.CharField(max_length=10)),
                ('selectstr', models.CharField(max_length=10)),
                ('techt', models.CharField(max_length=10)),
                ('tricky', models.CharField(max_length=10)),
                ('spinweb', models.CharField(max_length=10)),
                ('ithon', models.CharField(max_length=10)),
                ('dreams', models.CharField(max_length=10)),
                ('droneai', models.CharField(max_length=10)),
                ('wordwiz', models.CharField(max_length=10)),
                ('sanklp', models.CharField(max_length=10)),
                ('prodigai', models.CharField(max_length=10)),
                ('woedblk', models.CharField(max_length=10)),
                ('mathbz', models.CharField(max_length=10)),
                ('jam', models.CharField(max_length=10)),
                ('quiz', models.CharField(max_length=10)),
                ('webdes', models.CharField(max_length=10)),
                ('postdes', models.CharField(max_length=10)),
                ('codewar', models.CharField(max_length=10)),
                ('dpquer', models.CharField(max_length=10)),
                ('innovatr', models.CharField(max_length=10)),
                ('techsi', models.CharField(max_length=10)),
                ('iplauc', models.CharField(max_length=10)),
                ('bgmi', models.CharField(max_length=10)),
                ('squid', models.CharField(max_length=10)),
                ('ludo', models.CharField(max_length=10)),
                ('quizcomb', models.CharField(max_length=10)),
                ('onemorepls', models.CharField(max_length=10)),
                ('handsup', models.CharField(max_length=10)),
                ('chunk', models.CharField(max_length=10)),
                ('myclay', models.CharField(max_length=10)),
                ('rushup', models.CharField(max_length=10)),
                ('spellb', models.CharField(max_length=10)),
                ('phtophon', models.CharField(max_length=10)),
                ('suduko', models.CharField(max_length=10)),
                ('smashkrts', models.CharField(max_length=10)),
                ('dhumcrds', models.CharField(max_length=10)),
                ('thugof', models.CharField(max_length=10)),
                ('lemonspn', models.CharField(max_length=10)),
                ('esports', models.CharField(max_length=10)),
                ('badmnton', models.CharField(max_length=10)),
                ('volleybl', models.CharField(max_length=10)),
                ('crckt', models.CharField(max_length=10)),
                ('foodchlng', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
